[repository]
name = "hypr-hot-edge"
authors = ["claychinasky"]
commit_pins = []

[hypr-hot-edge]
description = "Hot edge trigger for sliding special workspace overlays"
output = "build/hypr-hot-edge.so"
build = [
    "cmake -B build",
    "cmake --build build -j`nproc`"
]
